package com.krish.hadoop.counter;

public enum CounterEnum {
	TOTALPRICE_LESS_AVERAGE, TOTALPRICE_MORE_AVERAGE_LESS_DOUBLE_AVERAGE, TOTALPRICE_MORE_DOUBLE_AVERAGE, QTY_LESS_10, QTY_MORE_10, PRICE_LESS_25, PRICE_MORE_25_LESS_100, PRICE_MORE_100
}
